baseurl = "http://flowstatestudio.github.io/LizHallComedy/"
languageCode = "en-us"
title = "Liz Hall"
theme = "hugo-creative-theme"

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more informtion take a look at the README.

	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Liz Hall"
	description = "Stand up comedian"


	# Navigation
	[params.navigation]
		brand = "My feet are mad swole."

		[params.navigation.links]
			about     = "About"
			shows     = "Shows"
			videos    = "Videos"
			podcast   = "Podcast"
			contact   = "Contact"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "Liz Hall"
		subtitle   = "Seriously, who gives their child a kazoo?"
		buttonText = "Upcoming Shows"


	# About section
	[params.about]
		headline    = "Hilarious!"
		description = "Shit. All of that positivity earlier was just too much caffeine."
		buttonText  = "Contact Liz"
./de
	# Shows section
	[params.shows]
		headline = "Upcoming Shows"

     [[params.shows.list]]
      date = "3/23/2016 8pm"
			venue = "Porgie & Jess Comedy Show: Catman vs Superman, RAKit CLUB, Bushwick, Brooklyn"
     [[params.shows.list]]
      date = "3/24/2016 8pm"
			venue = "No Sugar Tonight, Teafee Coffee Shop, Court St. Brooklyn"
     [[params.shows.list]]
      date = "3/28/2016 6pm"
			venue = "Giggle Pit, Klimat Lounge, Manhattan"
     [[params.shows.list]]
     	date = "3/30/2016 7pm"
			venue = "Laughing at Life, Pianos, Ludlow St, NY"
     [[params.shows.list]]
     	date = "3/31/2016 9:30pm"
			venue = "Level 8: A Comedy Variety Series, The Tank, 151 W46th St 8th Floor, NY NY"
     [[params.shows.list]]
     	date = "4/11/2016 7:30pm"
			venue = "The Stand, NY"
			tickets = "http://events.constantcontact.com/register/event?llr=mvldmqdab&oeidk=a07ecgpg0ge2ce417f1"



	# videos section
	[params.videos]
		headline = "Videos"

	  [[params.videos.list]]
	  id = "BbzHIJ77z68"

	  [[params.videos.list]]
	  id = "oXR_nhbSuLI"

	# podcast section
	[params.podcast]
	  headline = "Podcast"
    cover = "http://www.bizarr2d2.com/pod/cover2.jpg"

	  [[params.podcast.list]]
	  icon = "fa-apple"
	  title = "iTunes"
	  link = "https://itunes.apple.com/us/podcast/coming-in-sideways/id805612135"

	  [[params.podcast.list]]
	  icon = "fa-headphones"
	  title = "Stitcher"
	  link = "http://www.stitcher.com/podcast/oakley-hall-2/coming-in-sideways"

	  [[params.podcast.list]]
	  icon = "fa-youtube-square"
	  title = "YouTube"
	  link = "https://www.youtube.com/channel/UCV7Cmcrjv_qeXy_RWB2ykag"


	# Contact section
	[params.contact]
		headline = "Contact"
		description = "Email for booking info"
		email = "hall.liz@gmail.com"
		twitter = "https://twitter.com/lizhall349"
		facebook = "https://www.facebook.com/elizabeth.hall.5074"
    youtube = "https://www.youtube.com/channel/UCV7Cmcrjv_qeXy_RWB2ykag"
    instagram = "https://instagram.com/lizhall349/"