baseurl = "http://flowstatestudio.github.io/LizHallComedy/"
languageCode = "en-us"
title = "Liz Hall"
theme = "hugo-creative-theme"

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more informtion take a look at the README.

	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Liz Hall"
	description = "Stand up comedian"
  favicon = "favicon.ico"


	# Navigation
	[params.navigation]
		brand = "My feet are mad swole."

		[params.navigation.links]
			about     = "About"
			shows     = "Shows"
			videos    = "Videos"
			podcast   = "Podcast"
			contact   = "Contact"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "Liz Hall"
		subtitle   = "Seriously, who gives their child a kazoo?"
		buttonText = "Shows"


	# About section
	[params.about]
		headline    = "Hilarious!"
		description = "Shit. All of that positivity earlier was just too much caffeine."
		buttonText  = "Contact Liz"

	# Shows section
	[params.shows]
		headline = "Shows"
     [[params.shows.list]]
      date = "3/16/2018 8pm"
      venue = "Comedy Camp w Liz & Glo"

     [[params.shows.list]]
      date = "3/10/2018 7:30pm"
      venue = "The Revolution @ QED Astoria"

     [[params.shows.list]]
      date = "2/24/2018 8pm"
      venue = "Kindred Sluts @ Club Cumming"

     [[params.shows.list]]
      date = "1/11/2018 9:30pm"
      venue = "Home Cooked Comedy @ The Five Spot"

     [[params.shows.list]]
      date = "3/25/2017 7pm"
      venue = "Backfat Comedy Present March Madness One-Liner Jokes Contest. Semi-Finalist"

     [[params.shows.list]]
      date = "4/7/4017 9pm"
      venue = "Home Cooked Comedy @ The Five Spot"

     [[params.shows.list]]
      date = "4/20/2017 11pm"
      venue = "Stand Up NY"

     [[params.shows.list]]
      date = "4/21/2017 7pm"
      venue = "Comedy at Cafe Forte"

     [[params.shows.list]]
      date = "4/22/2017 8:30pm"
      venue = "Sidewalk Cafe"

     [[params.shows.list]]
      date = "5/20/2017 8pm"
      venue = "Comedy Camp w Liz & Glo"

     [[params.shows.list]]
      date = "5/21/2017 8pm"
      venue = "Greenwich Village Comedy Club"


	# videos section
	[params.videos]
		headline = "Videos"

	  [[params.videos.list]]
	  id = "YMMIbhCfArE&"

	  [[params.videos.list]]
	  id = "sK-1sn-kBEg"

	  [[params.videos.list]]
	  id = "BbzHIJ77z68"

	  [[params.videos.list]]
	  id = "oXR_nhbSuLI"

	# podcast section
	[params.podcast]
	  headline = "Podcast"
    cover = "https://pbs.twimg.com/profile_images/428028588982423552/cdsPTscP.jpeg"

	  [[params.podcast.list]]
	  icon = "fa-apple"
	  title = "iTunes"
	  link = "https://itunes.apple.com/us/podcast/coming-in-sideways/id805612135"

	  [[params.podcast.list]]
	  icon = "fa-headphones"
	  title = "Stitcher"
	  link = "http://www.stitcher.com/podcast/oakley-hall-2/coming-in-sideways"

	  [[params.podcast.list]]
	  icon = "fa-youtube-square"
	  title = "YouTube"
	  link = "https://www.youtube.com/channel/UCV7Cmcrjv_qeXy_RWB2ykag"


	# Contact section
	[params.contact]
		headline = "Contact"
		description = "Email for booking info"
		email = "hall.liz@gmail.com"
		twitter = "https://twitter.com/lizhall349"
		facebook = "https://www.facebook.com/elizabeth.hall.5074"
    youtube = "https://www.youtube.com/channel/UCV7Cmcrjv_qeXy_RWB2ykag"
    instagram = "https://instagram.com/lizhall349/"