baseurl = "http://flowstatestudio.github.io/LizHallComedy/"
languageCode = "en-us"
title = "Liz Hall"
theme = "hugo-creative-theme"

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more informtion take a look at the README.

	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Liz Hall"
	description = "Stand up comedian"


	# Navigation
	[params.navigation]
		brand = "My feet are mad swole."

		[params.navigation.links]
			about     = "About"
			shows     = "Shows"
			videos    = "Videos"
			podcast   = "Podcast"
			contact   = "Contact"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "Liz Hall"
		subtitle   = "Seriously, who gives their child a kazoo?"
		buttonText = "Shows"


	# About section
	[params.about]
		headline    = "Hilarious!"
		description = "Shit. All of that positivity earlier was just too much caffeine."
		buttonText  = "Contact Liz"

	# Shows section
	[params.shows]
		headline = "Shows"

     [[params.shows.list]]
      date = "10/13/2016 8pm"
			venue = "Domo ArtiTaco, Domo Taco, Brooklyn, NY"

     [[params.shows.list]]
      date = "10/20/2016 8:30pm"
			venue = "Comedy at the Corner, Hungry Ghost Cafe, Brooklyn"

     [[params.shows.list]]
      date = "10/23/2016 7:30pm"
			venue = "Church! Bunga's Den, New York, NY"

     [[params.shows.list]]
      date = "10/25/2016 8:30pm"
			venue = "Dangerfield's, New York, NY"

     [[params.shows.list]]
      date = "10/27/2016 8pm"
			venue = "Hoboken Bar and Grill, Benefit Comedy Show for the Hoboken Animal Shelter"

     [[params.shows.list]]
      date = "11/3/2016 8pm"
			venue = "Penance, A Comedy Show! Halyards Bar, Brooklyn	Donations go to: http://wheelingforward.org/"

     [[params.shows.list]]
      date = "12/10/2016 8pm
			venue = "Six Pack @ Brit Pack"
			tickets = "https://www.eventbrite.com/e/free-drinks-open-bar-6pack-at-britpack-comedy-showcase-121016-tickets-28618234911"


	# videos section
	[params.videos]
		headline = "Videos"

	  [[params.videos.list]]
	  id = "BbzHIJ77z68"

	  [[params.videos.list]]
	  id = "oXR_nhbSuLI"

	# podcast section
	[params.podcast]
	  headline = "Podcast"
    cover = "http://www.bizarr2d2.com/pod/cover2.jpg"

	  [[params.podcast.list]]
	  icon = "fa-apple"
	  title = "iTunes"
	  link = "https://itunes.apple.com/us/podcast/coming-in-sideways/id805612135"

	  [[params.podcast.list]]
	  icon = "fa-headphones"
	  title = "Stitcher"
	  link = "http://www.stitcher.com/podcast/oakley-hall-2/coming-in-sideways"

	  [[params.podcast.list]]
	  icon = "fa-youtube-square"
	  title = "YouTube"
	  link = "https://www.youtube.com/channel/UCV7Cmcrjv_qeXy_RWB2ykag"


	# Contact section
	[params.contact]
		headline = "Contact"
		description = "Email for booking info"
		email = "hall.liz@gmail.com"
		twitter = "https://twitter.com/lizhall349"
		facebook = "https://www.facebook.com/elizabeth.hall.5074"
    youtube = "https://www.youtube.com/channel/UCV7Cmcrjv_qeXy_RWB2ykag"
    instagram = "https://instagram.com/lizhall349/"